### ISSUE TITLE
Using quackling with LangChain

### ISSUE THREAD

**Issue by tansut** [DS4SD/quackling#12]
Hi,

Is there any sample demonstrating usage with langchain?

-tansu

**Comment by vagenas** [comment]
Hi @tansut, LangChain integration has just been introduced with [v0.4.0](https://github.com/DS4SD/quackling/releases/tag/v0.4.0). 
You can find a basic example [here](https://github.com/DS4SD/quackling/blob/main/examples/langchain/basic_pipeline.ipynb).

If this answers your question, feel free to close the issue.

**Comment by tansut** [comment]
Thanks.
